title: GO-JUMP.SITE
description: Cтрибки з мотузкою в Києві
summary: Постійно стрибаємо ст.м. Поштова - "Парковий міст"
phone: ‎+38 (096) 388-22-08

# Certificate expire date
cert_expire_date: 2021-10-31

#Prices
payment:
  jump_classic:
    enabled: false
    amount: 400
    description: Бронювання одиночного стрибка
  jump_tandem:
    enabled: false
    amount: 900
    description: Бронювання тандем стрибка
  cert_classic:
    enabled: false
    amount: 450
    description: Сертифікат на одиночний стрибок
  cert_tandem:
    enabled: false
    amount: 950
    description: Сертифікат на тандем стрибок

# Telegram config
telegram_chatId: 492010472
# telegram_chatId: 353354751 # filko
telegram_bot_token: 983495413:AAECuNOKh00LLeaCxpzHIxzBEW0JL1upSFU

show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

dates:
  - 2023-05-26
  - 2023-05-27
  - 2023-05-28
  - 2021-06-02
  - 2021-06-03
  - 2021-06-04
  - 2021-06-09
  - 2021-06-10
