title: GO-JUMP.COM.UA
description: Прыжки с веревкой. Киев
summary: Регулярно прыгаем ст.м. Почтовая - "Парковый мост"
phone: ‎+38 (096) 388-22-08

# Certificate expire date
cert_expire_date: 2020-11-10

#Prices
payment:
  jump_classic:
    enabled: false
    amount: 250
    description: Бронирование классического прыжка
  jump_tandem:
    enabled: false
    amount: 550
    description: Бронирование тандем прыжка
  cert_classic:
    enabled: true
    amount: 300
    description: Сертификат на классический прыжок
  cert_tandem:
    enabled: true
    amount: 600
    description: Сертификат на тандем прыжок

# Telegram config
telegram_chatId: 492010472
#telegram_chatId: 353354751 # filko
telegram_bot_token: 983495413:AAECuNOKh00LLeaCxpzHIxzBEW0JL1upSFU

show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

dates:
  - 2019-09-30
  - 2019-10-02
  - 2019-10-03
  - 2019-10-04
  - 2019-10-05
  - 2019-10-06
  - 2019-10-07
  - 2019-10-08
