title: ROPE-JUMPING.KYIV.UA
description: Cтрибки з мотузкою в Києві
summary: Постійно стрибаємо ст.м. Поштова - "Парковий міст"
phone: ‎+38 (096) 388-22-08

# Certificate expire date
cert_expire_date: 2026-10-11

#Prices
payment:
  jump_classic:
    enabled: false
    amount: 700
    description: Бронювання одиночного стрибка
  jump_tandem:
    enabled: false
    amount: 1500
    description: Бронювання тандем стрибка
  cert_classic:
    enabled: false
    amount: 800
    description: Сертифікат на одиночний стрибок
  cert_tandem:
    enabled: false
    amount: 1600
    description: Сертифікат на тандем стрибок

# Telegram config
telegram_chatId: 492010472
# telegram_chatId: 353354751 # filko
telegram_bot_token: 983495413:AAECuNOKh00LLeaCxpzHIxzBEW0JL1upSFU

show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

dates:
  - 2025-10-18
  - 2025-10-19
  - 2025-10-25
  - 2025-10-26
  - 2025-11-01
  - 2025-11-02
  - 2026-05-01
  - 2026-05-02
