title: ROPE-JUMPING.KYIV.UA
description: Cтрибки з мотузкою в Києві
summary: Постійно стрибаємо ст.м. Поштова - "Парковий міст"
phone: ‎+38 (096) 388-22-08

# Certificate expire date
cert_expire_date: 2025-10-12

#Prices
payment:
  jump_classic:
    enabled: false
    amount: 700
    description: Бронювання одиночного стрибка
  jump_tandem:
    enabled: false
    amount: 1500
    description: Бронювання тандем стрибка
  cert_classic:
    enabled: false
    amount: 800
    description: Сертифікат на одиночний стрибок
  cert_tandem:
    enabled: false
    amount: 1600
    description: Сертифікат на тандем стрибок

# Telegram config
telegram_chatId: 492010472
# telegram_chatId: 353354751 # filko
telegram_bot_token: 983495413:AAECuNOKh00LLeaCxpzHIxzBEW0JL1upSFU

show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

dates:
  - 2024-07-31
  - 2024-08-01
  - 2024-08-02
  - 2024-08-03
  - 2024-08-06
  - 2024-08-07
  - 2024-08-08
  - 2024-08-09
