title: ROPE-JUMPING.KYIV.UA
description: Cтрибки з мотузкою в Києві
summary: Постійно стрибаємо ст.м. Поштова - "Парковий міст"
phone: ‎+38 (096) 388-22-08

# Certificate expire date
cert_expire_date: 2024-10-13

#Prices
payment:
  jump_classic:
    enabled: false
    amount: 600
    description: Бронювання одиночного стрибка
  jump_tandem:
    enabled: false
    amount: 1500
    description: Бронювання тандем стрибка
  cert_classic:
    enabled: false
    amount: 700
    description: Сертифікат на одиночний стрибок
  cert_tandem:
    enabled: false
    amount: 1600
    description: Сертифікат на тандем стрибок

# Telegram config
telegram_chatId: 492010472
# telegram_chatId: 353354751 # filko
telegram_bot_token: 983495413:AAECuNOKh00LLeaCxpzHIxzBEW0JL1upSFU

show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

dates:
  - 2024-09-28
  - 2024-09-29
  - 2024-10-04
  - 2024-10-05
  - 2024-10-06
  - 2024-10-11
  - 2024-10-12
  - 2024-10-13
