title: GO-JUMP.SITE
description: Cтрибки з мотузкою в Києві
summary: Постійно стрибаємо ст.м. Поштова - "Парковий міст"
phone: ‎+38 (096) 388-22-08

# Certificate expire date
cert_expire_date: 2023-08-31

#Prices
payment:
  jump_classic:
    enabled: false
    amount: 500
    description: Бронювання одиночного стрибка
  jump_tandem:
    enabled: false
    amount: 1200
    description: Бронювання тандем стрибка
  cert_classic:
    enabled: false
    amount: 550
    description: Сертифікат на одиночний стрибок
  cert_tandem:
    enabled: false
    amount: 1250
    description: Сертифікат на тандем стрибок

# Telegram config
telegram_chatId: 492010472
# telegram_chatId: 353354751 # filko
telegram_bot_token: 983495413:AAECuNOKh00LLeaCxpzHIxzBEW0JL1upSFU

show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

dates:
  - 2023-06-30
  - 2023-07-01
  - 2023-07-02
  - 2021-07-07
  - 2021-07-08
  - 2021-07-09
  - 2021-07-14
  - 2021-07-15
