title: GO-JUMP.COM.UA
description: Прыжки с веревкой. Киев
summary: Регулярно прыгаем ст.м. Почтовая - "Парковый мост"
phone: ‎+38 (096) 388-22-08

# Certificate expire date
cert_expire_date: 2021-10-31

#Prices
payment:
  jump_classic:
    enabled: false
    amount: 300
    description: Бронирование классического прыжка
  jump_tandem:
    enabled: false
    amount: 700
    description: Бронирование тандем прыжка
  cert_classic:
    enabled: false
    amount: 350
    description: Сертификат на классический прыжок
  cert_tandem:
    enabled: false
    amount: 750
    description: Сертификат на тандем прыжок

# Telegram config
# telegram_chatId: 492010472
telegram_chatId: 353354751 # filko
telegram_bot_token: 983495413:AAECuNOKh00LLeaCxpzHIxzBEW0JL1upSFU

show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

dates:
  - 2021-06-03
  - 2021-06-04
  - 2021-06-05
  - 2021-06-06
  - 2021-06-07
  - 2021-06-08
  - 2021-06-09
  - 2021-06-10
