title: GO-JUMP.COM.UA
description: Прыжки с веревкой. Киев
summary: Регулярно прыгаем ст.м. Почтовая - "Парковый мост"
phone: ‎+38 (096) 388-22-08

show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

dates:
  - 2019-09-30
  - 2019-10-02
  - 2019-10-03
  - 2019-10-04
  - 2019-10-05
  - 2019-10-06
  - 2019-10-07
  - 2019-10-08
