title: GO-JUMP.COM.UA
description: Прыжки с веревкой. Киев
summary: Регулярно прыгаем ст.м. Почтовая - "Парковый мост"
phone: ‎+38 (096) 388-22-08

show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
